shadow_tc: #namespace

    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 1000

    n_actions: 8 # Increase and decrease 7 joints.

    movement_delta: 0.01 # Movement Variation of the TCP position for each step in meters.
    
    work_space: # 3D cube in which Sawyers TCP ( right_electric_gripper_base frame) is allowed to move in
      x_max: 0.3
      x_min: -0.5
      y_max: 0.19
      y_min: -0.45
      z_max: 1.6
      z_min: 1.1


    acceptable_distance_to_ball: 0.03 # Distance to the ball that we consider that it reached the ball.
    
    number_decimals_precision_obs: 2

    done_reward: 1000.0 # reward
    closer_to_block_reward: 100.0 # reward